Updates and exclude folders option
matejchalk/vscode-material-icons pull request #2
Opened 2024-12-10 17:28 UTC by vmasek

-

2024-12-11 16:40 UTC, matejchalk requested changes

2024-12-11 16:40 UTC, matejchalk commented on package-lock.json
The Vercel deployment failed because of an optional dependency. I get the same error locally. Maybe re-creating `package-lock.json` will help?

> npm error Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

![image](https://github.com/user-attachments/assets/797d0cf8-9933-4d04-bb42-77ff0161f251)

2024-12-11 16:40 UTC, matejchalk commented on src/routes/+page.server.ts
> +  );
So you don't create the `URL` twice:

```suggestion
  const { searchParams } = new URL(request.url);
  const term = searchParams.get('q');
  const excludeFolders = Boolean(
    searchParams.get('excludeFolders'),
  );
```

2024-12-11 16:40 UTC, matejchalk commented on src/routes/+layout.svelte
> +      console.log(document.location.origin);
Leftover from debugging?

```suggestion
```

2024-12-11 16:53 UTC, vmasek commented on package-lock.json
I see, it is the classic case of optional dep on CI error
https://github.com/vercel/vercel/issues/11665

2025-02-08 09:10 UTC, matejchalk approved these changes

2025-02-08 09:11 UTC, merged